### ISSUE TITLE
merge with awesome-pokemon?

### ISSUE THREAD

**Issue by tobiasbueschel** [ericwooley/AwesomePokemonGo#1]
Hi @ericwooley,

How is it going? :)

Really cool to see that other people are also creating / curating resources for Pokemon Go development! I have actually created an [awesome](https://github.com/sindresorhus/awesome) Pokemon list a while ago and was just wondering whether you would be interested to merge yours with mine for the sake of joining forces?

https://github.com/tobiasbueschel/awesome-pokemon

I suppose the more contributors a curated list has, the more useful it becomes for the community?

Best wishes

**Comment by ericwooley** [comment]
@tobiasbueschel I did not see this repo before! Thats way better than mine. I will check if anything on my list is not on that list, PR, and delete this one.

Thanks for letting me know.

**Comment by tobiasbueschel** [comment]
Hi @ericwooley,

no worries 👍 Glad you like the other repo! I'll review your PR and send some feedback! Thanks and have a good day!

Best,
Tobias
